#!/bin/sh
echo "Content-Type: application/json"
echo ""
/www/netmonitor/vnstati/vnstati.sh >/dev/null 2>&1
rm -f /etc/vnstat/vnstat.db
service vnstat restart
sleep 2
/www/netmonitor/vnstati/vnstati.sh
echo '{"success":true,"message":"Reset completed"}'
